// src/api/mock.ts
// Fixture data for MOCK_MODE. Must be structurally identical to real API responses.
// Covers all 3 testdata game IDs. Timeline has 12 plays across Q1-Q4 with varying
// win_prob values so WinProbChart has meaningful data to render.

import type { GameSummary, GameTimelineResponse } from './schemas'

export const MOCK_GAMES: GameSummary[] = [
  {
    game_id: '2011_01_NO_GB',
    home_team: 'GB',
    away_team: 'NO',
    home_score: 42,
    away_score: 34,
    duration: 3600,
  },
  {
    game_id: '2011_09_GB_SD',
    home_team: 'SD',
    away_team: 'GB',
    home_score: 38,
    away_score: 45,
    duration: 3600,
  },
  {
    game_id: '2011_14_OAK_GB',
    home_team: 'GB',
    away_team: 'OAK',
    home_score: 46,
    away_score: 16,
    duration: 3600,
  },
]

export const MOCK_TIMELINE: GameTimelineResponse = {
  game_id: '2011_01_NO_GB',
  home_team: 'GB',
  away_team: 'NO',
  max_tick: 3600,
  plays: [
    {
      tick: 0,
      quarter: 1,
      down: null,
      yards_to_go: null,
      yard_line: null,
      home_score: 0,
      away_score: 0,
      posteam: 'GB',
      win_prob: 0.5,
      play_type: 'kickoff',
      description: '(15:00) D.Masthay kicks 65 yards from GB 35 to NO 0. P.Thomas for 25 yards to NO 25.',
    },
    {
      tick: 120,
      quarter: 1,
      down: 1,
      yards_to_go: 10,
      yard_line: 75,
      home_score: 0,
      away_score: 0,
      posteam: 'NO',
      win_prob: 0.48,
      play_type: 'run',
      description: '(12:00) D.Thomas up the middle to NO 28 for 3 yards.',
    },
    {
      tick: 480,
      quarter: 1,
      down: 1,
      yards_to_go: 10,
      yard_line: 65,
      home_score: 7,
      away_score: 0,
      posteam: 'NO',
      win_prob: 0.42,
      play_type: 'pass',
      description: '(7:00) D.Brees pass short right to M.Colston to NO 42 for 7 yards.',
    },
    {
      tick: 900,
      quarter: 2,
      down: 1,
      yards_to_go: 10,
      yard_line: 60,
      home_score: 7,
      away_score: 7,
      posteam: 'GB',
      win_prob: 0.55,
      play_type: 'run',
      description: '(15:00) R.Grant up the middle to GB 42 for 4 yards.',
    },
    {
      tick: 1200,
      quarter: 2,
      down: 2,
      yards_to_go: 6,
      yard_line: 55,
      home_score: 14,
      away_score: 7,
      posteam: 'GB',
      win_prob: 0.62,
      play_type: 'pass',
      description: '(10:00) A.Rodgers pass short right to G.Jennings for 12 yards, TOUCHDOWN.',
    },
    {
      tick: 1620,
      quarter: 2,
      down: 3,
      yards_to_go: 8,
      yard_line: 45,
      home_score: 21,
      away_score: 17,
      posteam: 'NO',
      win_prob: 0.38,
      play_type: 'pass',
      description: '(3:00) D.Brees pass incomplete short left intended for R.Bush.',
    },
    {
      tick: 1800,
      quarter: 3,
      down: 1,
      yards_to_go: 10,
      yard_line: 80,
      home_score: 28,
      away_score: 17,
      posteam: 'NO',
      win_prob: 0.153,
      play_type: 'run',
      description: '(15:00) M.Ingram up the middle to NO 21 for 1 yard.',
    },
    {
      tick: 2100,
      quarter: 3,
      down: 1,
      yards_to_go: 10,
      yard_line: 70,
      home_score: 28,
      away_score: 24,
      posteam: 'NO',
      win_prob: 0.31,
      play_type: 'pass',
      description: '(10:00) D.Brees pass deep right to D.Thomas for 28 yards.',
    },
    {
      tick: 2700,
      quarter: 4,
      down: 1,
      yards_to_go: 10,
      yard_line: 50,
      home_score: 35,
      away_score: 24,
      posteam: 'GB',
      win_prob: 0.78,
      play_type: 'run',
      description: '(15:00) R.Grant left tackle to GB 52 for 2 yards.',
    },
    {
      tick: 3000,
      quarter: 4,
      down: 2,
      yards_to_go: 4,
      yard_line: 35,
      home_score: 42,
      away_score: 24,
      posteam: 'NO',
      win_prob: 0.12,
      play_type: 'pass',
      description: '(5:00) D.Brees pass short middle to J.Graham to GB 38 for -3 yards.',
    },
    {
      tick: 3300,
      quarter: 4,
      down: 1,
      yards_to_go: 10,
      yard_line: 20,
      home_score: 42,
      away_score: 34,
      posteam: 'NO',
      win_prob: 0.04,
      play_type: 'pass',
      description: '(5:00) D.Brees pass deep middle to D.Thomas for 18 yards, TOUCHDOWN.',
    },
    {
      tick: 3560,
      quarter: 4,
      down: null,
      yards_to_go: null,
      yard_line: null,
      home_score: 42,
      away_score: 34,
      posteam: null,
      win_prob: null,
      play_type: 'other',
      description: 'END GAME. Final: GB 42, NO 34.',
    },
  ],
}
